### ISSUE TITLE
Error: [NOTIFIER] Pushover notification failed.

### ISSUE THREAD

**Issue by mnbf9rca** [evilhero/mylar#1078]
I've requested my own API key and configured it in the GUI. I get the message "[NOTIFIER] Pushover notification failed.". mylar.log entries below:

```
29-Jun-2015 16:18:09 - INFO    :: Thread-12 : Sending Pushover notification
29-Jun-2015 16:18:10 - DEBUG   :: Thread-12 : PushOver response status: 404
29-Jun-2015 16:18:10 - DEBUG   :: Thread-12 : PushOver response headers: [('status', '404 Not Found'), ('content-length', '1960'), ('x-request-id', 'aaf76daf1b0643065e6daf5691628cec'), ('connection', 'close'), ('date', 'Mon, 29 Jun 2015 15:18:10 GMT'), ('content-type', 'text/html; charset=utf-8'), ('x-runtime', '0.002503')]
29-Jun-2015 16:18:10 - DEBUG   :: Thread-12 : PushOver response body: '<!DOCTYPE html>\n<html>\n<head>\n  <title>Pushover: Simple Mobile Notifications</title>\n  <link rel="shortcut icon" href="https://pushover.net/favicon.ico" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <link href="https://pushover.net/assets/application.css" media="all" rel="stylesheet" type="text/css" />\n  <script src="https://pushover.net/assets/application.js" type="text/javascript"></script>\n</head>\n<body>\n  <div id="whitey" class="">\n    <div class="navbar navbar-fixed-top">\n      <div class="navbar-inner">\n        <div class="container">\n          <a class="brand" href="https://pushover.net/" style="width: 83px; height: 18px;">\n            <img alt="Pushover" height="18"\n\t\t\t\tsrc="https://pushover.net/assets/writing-header.png"\n\t\t\t\tstyle="margin-bottom: -1px;" width="83" />\n          </a>\n        </div>\n      </div>\n    </div>\n\n    <div class="container" style="min-height: 400px;">\n  <div class="row">\n    <div class="span12">\n      <h2>Resource Not Found (or Incorrect Method)</h2>\n\n      <p>\n\t  The page or resource you requested could not be found.\n\t  </p>\n\t  <p>\n\t  If you are attempting an <a href="https://pushover.net/api">API</a> call,\n\t  verify the URL and the HTTP method (e.g., retry as a POST request instead\n\t  of GET).\n\t  </p>\n\t  <p>\n\t  Please try navigating through our <a\n\t  href="https://pushover.net/">homepage</a> or view our <a\n\t  href="https://pushover.net/api">API documentation</a>.\n      </p>\n    </div>\n  </div>\n</div>\n\n  </div>\n\n  <div class="dark_footer">\n    <div class="container" style="padding: 2em;">\n\n      <div class="row">\n        <div class="span6" id="trademark">\n          Pushover is a trademark and product of\n          <a href="http://superblock.net/">Superblock, LLC</a>.\n        </div>\n        <div class="span6" id="copyright">\n          Copyright &copy; 2012-2014 Superblock, LLC.  All rights reserved.\n        </div>\n      </div>\n\n    </div>\n  </div>\n</body>\n</html>\n'
29-Jun-2015 16:18:10 - INFO    :: Thread-12 : [NOTIFIER] Pushover notification failed.
```

**Comment by evilhero** [comment]
Probably need your update the module within mylar to accommodate the new methods. I don't use pushover so I haven't heard anything in regards to it not working until just now. I'll see what I can do to update things so it works.

**Comment by evilhero** [comment]
Just tested, and it works fine for me. Notified on snatch and as well as after successful post-processing.

What are your pushover settings ? As long as you have your API key for the new application you created (if that's what you did, and it's really beneficial to do it that way), and your User Key is correct within Mylar it shouldn't have any problems sending. Have you tried blanking out the API key that's provided with Mylar (or just leaving it blank if yours is in there), and trying ?

**Comment by mnbf9rca** [comment]
I did register a new API app wiht pushover (did you know you can create a
template app at pushover for others to clone from with their own API key?
You can then link to that for people to populate from). i'll try it at the
weekend with no key.

r.

**Comment by evilhero** [comment]
I wasn't aware of the template thing, although I just quickly tested it to make sure it was working so didn't really delve into the whole api they have there. I'll have to look into it abit more closely to see about linking in a template for general usage.

Are the pushovers still failling ?

**Comment by mnbf9rca** [comment]
i got sidetracked doing something else - i've cleared it and then readded my API and user keys. will wait and see what happens (woudl be good to have a "test" button too!)

**Comment by iheijoushin** [comment]
I believe this issue may not have been resolved as I am getting this error. I have verified the API/User key several times and tested a few Application API keys just in case. I also verified that Mylar's error is correct by double-checking Pushover's own logs and test messages are not being received.

**Comment by evilhero** [comment]
It is still working on my end - have you restarted mylar since you did the config changes? (Config changes usually need a restart of mylar to ensure things load properly).

What branch/commit are you running of mylar, and is it just the test button that's not working or does it notify on snatch/post-processing completion?

**Comment by iheijoushin** [comment]
Wow, thanks for the speedy reply! I hadn't tried restarting after putting in my Pushover details.

Things got even weirder after restarting Mylar - the message bubble that formerly contained the failure message is now empty (see attachment). The empty message bubble issue seems isolated to the Pushover Test button as checking for updates or other changes do correctly display text in the message bubble.

Any ideas? This is a fresh install as of about an hour ago. Pushover is nice but by no means a deal-breaker. :)

Here's the details from my version:
Mylar Version: master
-- git build e1bc2d9786392bfd1114b11e687ba792d6c5363b.
Python Version : 2.7.9

<img width="582" alt="untitled" src="https://cloud.githubusercontent.com/assets/5444980/12222719/840ff07c-b792-11e5-951f-31b7510d36e3.png">

**Comment by evilhero** [comment]
Yep that's the pushover module not returning the proper value to the gui.

This was fixed in the development branch,  but obviously it hasn't made it into the master yet given that error.

If you can switch branches, it would be better to be on the development just because it has alot of fixes that haven't made it into the master yet (it's also just as stable if not moreso, as I run that branch and if it's broken I'll fix it pretty quickly

**Comment by iheijoushin** [comment]
Thanks for the speedy reply. I switched to the development branch and am now running efe447f, but am still getting the blank error message shown in the screenshot above.

I haven't gotten downloading to work yet, so perhaps I am getting ahead of myself.

**Comment by cwhits** [comment]
pushover is working for me as long as I put the settings in config.ini. if I fill out the web ui it doesn't work.
