### ISSUE TITLE
Unable to complete Refreshing / Adding issue data (if half issues use a dash and not a period, ie 9-5 not 9.5)

### ISSUE THREAD

**Issue by foolsh** [evilhero/mylar#1237]
When an issue uses a dash instead of a period to notate a half issue, Mylar aborts with unable to complete

An example of a dash for half issue increments is http://comicvine.gamespot.com/elfquest-hidden-years/4050-4840/

```
07-Apr-2016 18:56:22 - INFO    :: Thread-13 : Now adding/updating issues for ElfQuest: Hidden Years
07-Apr-2016 18:56:22 - ERROR   :: Thread-13 : 9-5 this has an alpha-numeric in the issue # which I cannot account for.
07-Apr-2016 18:56:22 - WARNING :: Thread-13 : Unable to complete Refreshing / Adding issue data - this WILL create future problems if not addressed.
07-Apr-2016 18:56:37 - INFO    :: Thread-13 : Update complete
```

I just found this tonight, its a bummer too I wanted to read them on my tablet later tonight.  I haven't looked far enough into this to even know what file yet, but if someone wants to point me in it's direction it'd be much appreciated.

**Comment by evilhero** [comment]
That actually looks like a comicvine data problem. The issue is actually 9

**Comment by musictrivianut** [comment]
If I may, I'm having trouble getting Mylar to pick up any issues that are numbered ½.  Anytime that I refresh a comic with one of those issues, I always have to move it out to get Mylar to read the other issues.  If I forget, what follows is the error that it generates, with the pertinent line being the last one (yes, I verified that, in this case, the ½ was the 11th character).  That doesn't seem like a CV issue.  BTW, thanks for an otherwise great program.

Uncaught exception: Traceback (most recent call last):
File "$HOME/.mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "$HOME/.mylar/mylar/updater.py", line 781, in forceRescan
tmpval = filechecker.listFiles(dir=rescan['ComicLocation'], watchcomic=rescan['ComicName'], Publisher=rescan['ComicPublisher'], AlternateSearch=altnames)
File "$HOME/.mylar/mylar/filechecker.py", line 76, in listFiles
dirlist = traverse_directories(basedir)
File "$HOME/.mylar/mylar/filechecker.py", line 1230, in traverse_directories
for (dirname, subs, files) in os.walk(dir):
File "/usr/lib/python2.7/os.py", line 284, in walk
if isdir(join(top, name)):
File "/usr/lib/python2.7/posixpath.py", line 80, in join
path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 11: ordinal not in range(128)

**Comment by evilhero** [comment]
No the 9-5 is a CV issue as it isn't what the actual issue number is.  Your issue is completely different - albeit might look somewhat similar. 

Can I ask what the name of the file is that causes the error, as well as the debug logging that's generated for that particular issue when file checking (enable verbose logging first). 

And which branch of mylar are you running - currently the development branch had a new file checking method as opposed to the master which is using the original method.

**Comment by musictrivianut** [comment]
That particular file is named "Wolverine ½ (199601).cbz"


The log contents should be the same:


2016-04-08 23:16:08 INFO [FILE-RESCAN] Now checking files for Wolverine
(1988) in /media/wayne/Comics/comics/1988/Wolverine (1988)

2016-04-08 23:11:17 ERROR Uncaught exception: Traceback (most recent call
last):
File "/home/wayne/.mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/wayne/.mylar/mylar/updater.py", line 783, in forceRescan
tmpval = filechecker.listFiles(dir=rescan['ComicLocation'],
watchcomic=rescan['ComicName'], Publisher=rescan['ComicPublisher'],
AlternateSearch=altnames)
File "/home/wayne/.mylar/mylar/filechecker.py", line 78, in listFiles
dirlist = traverse_directories(basedir)
File "/home/wayne/.mylar/mylar/filechecker.py", line 1386, in
traverse_directories
for (dirname, subs, files) in os.walk(dir):
File "/usr/lib/python2.7/os.py", line 284, in walk
if isdir(join(top, name)):
File "/usr/lib/python2.7/posixpath.py", line 80, in join
path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 11:
ordinal not in range(128)
2016-04-08  INFO [FILE-RESCAN] Now checking files for Wolverine (1988) in
/media/wayne/Comics/comics/1988/Wolverine (1988)

Mylar version is: master
-- git build 8082a61f17100f022a3daa754c9f7a764ecf7a38.

Thanks.

**Comment by evilhero** [comment]
@foolsh: the 9-5 issue problem as it exists now on CV is now fixed in the development branch of Mylar (or when it gets pushed out soon it will be at least). I've modded Mylar to accomodate the 9-5, and autoconvert it to 9½ - I don't do this to any other issues on CV, so this is pretty much the epitome of a one-off exception to the rule ;)
```
09-Apr-2016 13:05:20 - INFO :: Thread-12 : Now adding/updating issues for ElfQuest: Hidden Years
09-Apr-2016 13:05:20 - DEBUG :: Thread-12 : issue: 9-5 is an invalid entry. Correcting to : 9½
09-Apr-2016 13:05:20 - DEBUG :: Thread-12 : initiating issue updating - just the info
```
![elfquest](https://cloud.githubusercontent.com/assets/909424/14405075/5a317466-fe54-11e5-8759-8fd7e598a671.png)

@musictrivianut : You probably want to be on the development branch - Mylar has recently switched to an entirely new file-checking process which intertwines with abunch of other modules for improved consistency across modules. I won't patch the master branch with a fix, since it's now using an outdated version of the filechecker, and the new filechecker in the development branch will be in the master branch in a few weeks (enough time to weed out the bugs). That being said it's fixed in the next development commit: 
![wolverine](https://cloud.githubusercontent.com/assets/909424/14405088/93c6df9a-fe54-11e5-9f6e-5ee500c81dbd.png)

**Comment by musictrivianut** [comment]
@evilhero : Well, the version (under settings) is still showing "master" so I don't know what I did wrong (use used the clone instructions under the wiki), but I installed the development branch and just refreshed the issue giving me problems and it worked just fine.  Thank you very much, sir.  And again, thank you for an awesome product.

**Comment by foolsh** [comment]
Thank you evilhero, awesome indeed!
