### ISSUE TITLE
clicking on Wanted tab give me Error 500 page

### ISSUE THREAD

**Issue by sukhysall** [evilhero/mylar#1405]
I get the following on the Wanted tab:

I'm running Mylar version: ed263d8784cb14859def1fd8cca479708f496013

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cprequest.py", line 645, in respond
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/lib/encoding.py", line 188, in __call__
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
  File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 1853, in upcoming
    if int(upc['weeknumber']) == int(weeknumber) and int(upc['year']) == int(weekyear):
TypeError: int() argument must be a string or a number, not 'NoneType'

thanks

**Comment by evilhero** [comment]
To get rid of the error, just go to your Weekly tab and do a Recreate pullist and it will line things up again.

I'll try and dereference it at some point today

**Comment by tchirou** [comment]
Hello
I updated this morning and have the same problem but I cannot access the "This week" page. It just tries and goes in a loop.
Is there any workaround ?
Thanks

**Comment by evilhero** [comment]
The middle site is off line, not sure on when it's coming back atm. Switch your alt_pull to either 0 or 1 in the config.ini (with mylar shut off) and it should fix the list so you can continue.

**Comment by tchirou** [comment]
I stopped, opend config.ini, I had alt_pull on 0, i put 1 and restarted but still the same problem (except I have the green light next to "This week")

**Comment by evilhero** [comment]
Put alt_pull to 2 as long as you're on the most recent development commit and it should drop back down to the lower alt pull options seeing as how the 2 method isn't available as of yet (it's coming back, just not sure of an eta)

**Comment by tchirou** [comment]
Sorry but I am on ed263d8784cb14859def1fd8cca479708f496013

But alt_pull with 2 does not fix the problem.

2016-10-05 23:13 GMT+02:00 evilhero <notifications@github.com>:

**Comment by evilhero** [comment]
Ok, so you're on Master - so you can't change it to alt_pull 2 to solve the issue since that just went up the other day for testing.

Flip the alt_pull back to 0, start up Mylar - let it finish loading everything up, and then click on the Weekly tab. It should let you view the listing and then you can do a Recreate Pullist. Make sure to put mylar into verbose/debug mode on startup so that you can get the debug logs and if it doesn't work, post in here the log with the error.

**Comment by tchirou** [comment]
Sorry but it still tries to load but nothing comes up
I can't find how to enbale the debug log in the settings or the config.ini
Could you please point me to it ?
Thanks

2016-10-06 15:26 GMT+02:00 evilhero <notifications@github.com>:

**Comment by evilhero** [comment]
Ugh OK this slipped thru dev and is in master so I have to do some quick code rework and push it directly to master without screwing up dev lol. 

Think I have it fixed in my local repo, gonna push it momentarily.

**Comment by tchirou** [comment]
Ok I updated and recreated the pullist
So the this week tab works
But the wanted tab does not work on purpose for the moment, right ?

Le 6 oct. 2016 à 16:48, evilhero <notifications@github.com> a écrit :

Ugh OK this slipped thru dev and is in master so I have to do some quick
code rework and push it directly to master without screwing up dev lol.

Think I have it fixed in my local repo, gonna push it momentarily.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/evilhero/mylar/issues/1405#issuecomment-251985555>, or mute
the thread

**Comment by evilhero** [comment]
No the Wanted tab works just fine. If you recreated the pull-list, you should have no problems accessing the Wanted tab.

**Comment by tchirou** [comment]
When I am on the home page, the link for the wanted tab is /home#
When I am on the this week page, the link for the wanted tab is /pullist#
I tried several times to recreate the pullist but it does not change a
thing unfortunately
Sorry to bother you but I don't know what to do

Le 6 oct. 2016 à 20:39, evilhero <notifications@github.com> a écrit :

No the Wanted tab works just fine. If you recreated the pull-list, you
should have no problems accessing the Wanted tab.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/evilhero/mylar/issues/1405#issuecomment-252051660>, or mute
the thread

**Comment by evilhero** [comment]
you're looking at the current url of the page you're on. Home = /home, pullist = /pullist, wanted = /upcoming.

You need to click on the actual Wanted tab regardless of the screen you're on to go to the specific tab.

If you're recreating the Pullist, you need to open the Weekly tab and then click on the Recreate Pullist option and wait for it to complete.

**Comment by tchirou** [comment]
I needed to restart after recreating the pullist
Now the wanted tab works
Thanks

Le 6 oct. 2016 à 20:46, evilhero <notifications@github.com> a écrit :

you're looking at the current url of the page you're on. Home = /home,
pullist = /pullist, wanted = /upcoming.

You need to click on the actual Wanted tab regardless of the screen you're
on to go to the specific tab.

If you're recreating the Pullist, you need to open the Weekly tab and then
click on the Recreate Pullist option and wait for it to complete.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/evilhero/mylar/issues/1405#issuecomment-252053482>, or mute
the thread
