### ISSUE TITLE
Error on cbr 2 cbz conversion

### ISSUE THREAD

**Issue by Finch106** [evilhero/mylar#1574]
[POST-PROCESSING] Sucessfully wrote metadata to .cbz (Error deleting original RAR after export 
The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz) - Continuing..

Verified cache folder has both cbr and converted cbz, they're just not moving out of cache/deleting. I'm the Admin on my Windows 10 machine and have checked other threads, but didn't see where the actual conversion occurred successfully.

Mylar Version: master
-- git build 44cd0de31f40f8324278ea6c5c6b3e97cfc94f8c.
Python Version : 2.7.13

**Comment by evilhero** [comment]
It might be dependent on how you're doing the post-processing - I just tried manual post-processing on a windows machine and it cleaned up the cache folders fine (win 10/admin). The weird part, is that error message shouldn't be part of the filname, which is what it's taking it as for some reason and I'm not sure why atm (I'm going to guess that you're doing a sab/nzbget download + post-process).

Can you put mylar into verbose/debug mode (-v switch on startup, or toggle verbose on in the Log GUI within Mylar), and then do the post-processing method you're trying again and post the resulting log ?

**Comment by Gamer106** [comment]
I've only recently enabled metadata tagging/conversion because Chunky was not correctly reading some files, but the only ones that have come down so far are Torrent.

21-Feb-2017 13:35:19 - INFO    :: CP Server Thread-6 : Starting postprocessing for : Manual Run
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] nzb name: Manual Run
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] nzb folder: D:\Complete\comics
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] Not using SABnzbd : Manual Run
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] Manual Run initiated
21-Feb-2017 13:35:19 - INFO    :: Thread-14 : there are 1 files.
21-Feb-2017 13:35:19 - INFO    :: Thread-14 : [FILENAME]: The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbr
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : Scanner group tag discovered: BlackManta-Empire
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : checking date : 2016
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : date: 2016
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : datecheck: [{'date': '2016', 'position': 3, 'mod_position': 17}]
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : sctd: 2017
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : year verified as : 2016
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : year verified as: 2016
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : highest_series_position: 3
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : possible_issuenumbers: [{'position': 2, 'validcountchk': False, 'number': '008', 'mod_position': 13}]
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : issue_position: 2
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : issue verified as : 008
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : series title possibly: The Punisher
21-Feb-2017 13:35:19 - INFO    :: Thread-14 : I have located 1 files that I should be able to post-process. Continuing...
21-Feb-2017 13:35:19 - INFO    :: Thread-14 : Series_Name: The Punisher --- WatchComic: The Punisher
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [MATCH: The Punisher] The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbr
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING][ISSUE-VERIFY] Now checking against The Punisher-90118
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING][ISSUE-VERIFY][Lone Volume FAILURE] Volume label of v8 indicates that there is more than one volume for this series, but the one on your watchlist has no volume label set.
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING][ISSUE-VERIFY][Issue Year FAILURE] Issue Year of 2017 does NOT match the year found in the filename of : 2016
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING][ISSUE-VERIFY] Checking against complete date to see if month published could allow for different publication year.
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING][ISSUE-VERIFY][Issue Year MATCH] Modified Issue Year of 2016 is a match to the year found in the filename of : 2016
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING][SUCCESSFUL MATCH: The Punisher-90118] Match verified for The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbr
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] Now Checking if the issue also resides in one of the storyarc's that I am watching.
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] There are 1 files found that match on your watchlist, 0 do not match anything.
21-Feb-2017 13:35:19 - INFO    :: Thread-14 : [DUPECHECK] Duplicate check for D:\Complete\comics\The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbr
21-Feb-2017 13:35:19 - INFO    :: Thread-14 : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
21-Feb-2017 13:35:19 - INFO    :: Thread-14 : [POST-PROCESSING] [1/1] Starting Post-Processing for The Punisher issue: 8
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] issueid: 578470
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] issuenumOG: 8
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] Zero Suppression set to : none
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : issue detected less than 10
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : Zero level supplement set to none. Issue will be set as : 8
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] Pretty Comic Issue is : 8
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] Issue Year : 2017
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] Publisher: Marvel
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] Series: The Punisher
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] Year: 2016
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] Comic Location: D:\Media\Books\Comics\The Punisher (2016)
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] Comic Version: v8
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] Not an annual - removing from filename parameters
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] New format: $Series $Issue ($Year)
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [POST-PROCESSING] Metatagging enabled - proceeding...
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [META-TAGGER] dirName:D:\Complete\comics
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : ComicTagger Path location for internal comictagger.py set to : c:\Mylar\comictagger.py
21-Feb-2017 13:35:19 - DEBUG   :: Thread-14 : [META-TAGGER] Filename is : D:\Complete\comics\The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbr
21-Feb-2017 13:35:20 - DEBUG   :: Thread-14 : [META-TAGGER] Paths / Locations:
21-Feb-2017 13:35:20 - DEBUG   :: Thread-14 : [META-TAGGER] scriptname : Mylar.py
21-Feb-2017 13:35:20 - DEBUG   :: Thread-14 : [META-TAGGER] downloadpath : D:\Complete\comics
21-Feb-2017 13:35:20 - DEBUG   :: Thread-14 : [META-TAGGER] sabnzbdscriptpath : c:\Mylar
21-Feb-2017 13:35:20 - DEBUG   :: Thread-14 : [META-TAGGER] comicpath : C:\Mylar\cache\mylar_7gyowx
21-Feb-2017 13:35:20 - DEBUG   :: Thread-14 : [META-TAGGER] Running the ComicTagger Add-on for Mylar
21-Feb-2017 13:35:27 - DEBUG   :: Thread-14 : [META-TAGGER] ComicTagger 1.20.1 [ninjas.walk.alone / SHURIKEN]
 being used - using personal ComicVine API key supplied via mylar.
21-Feb-2017 13:35:28 - DEBUG   :: Thread-14 : [META-TAGGER] CR Tagging enabled.
21-Feb-2017 13:35:28 - DEBUG   :: Thread-14 : [META-TAGGER] Enabling ComicTagger script: ['c:\\Python27\\python.exe', 'c:\\Mylar\\comictagger.py'] with options: ['-e', '--delete-rar', u'C:\\Mylar\\cache\\mylar_7gyowx\\The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbr']
21-Feb-2017 13:35:28 - DEBUG   :: Thread-14 : [META-TAGGER] Executing command: ['c:\\Python27\\python.exe', 'c:\\Mylar\\comictagger.py', '-e', '--delete-rar', u'C:\\Mylar\\cache\\mylar_7gyowx\\The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbr']
21-Feb-2017 13:35:28 - DEBUG   :: Thread-14 : [META-TAGGER] Absolute path to script: c:\Python27\python.exe
21-Feb-2017 13:35:31 - DEBUG   :: Thread-14 : [META-TAGGER][COMIC-TAGGER] : Error deleting original RAR after export

Archive exported successfully to: The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz


21-Feb-2017 13:35:31 - DEBUG   :: Thread-14 : [META-TAGGER]Trying utf-8 conversion.
21-Feb-2017 13:35:31 - DEBUG   :: Thread-14 : [META-TAGGER]Trying latin-1 conversion.
21-Feb-2017 13:35:31 - DEBUG   :: Thread-14 : [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] New filename: C:\Mylar\cache\mylar_7gyowx\Error deleting original RAR after export

The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz
21-Feb-2017 13:35:31 - INFO    :: Thread-14 : [META-TAGGER] ComicRack tagging meta-tagging processing started.
21-Feb-2017 13:35:31 - DEBUG   :: Thread-14 : [META-TAGGER] Enabling ComicTagger script: ['c:\\Python27\\python.exe', 'c:\\Mylar\\comictagger.py'] with options: ['-s', '-m', 'volume=8', '--cv-api-key', u'REDACTED', '-o', '--id', u'578470', '--type', 'cr', u'C:\\Mylar\\cache\\mylar_7gyowx\\Error deleting original RAR after export\r\nThe Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz']
21-Feb-2017 13:35:31 - DEBUG   :: Thread-14 : [META-TAGGER] Executing command: ['c:\\Python27\\python.exe', 'c:\\Mylar\\comictagger.py', '-s', '-m', 'volume=8', '--cv-api-key', u'REDACTED', '-o', '--id', u'578470', '--type', 'cr', u'C:\\Mylar\\cache\\mylar_7gyowx\\Error deleting original RAR after export\r\nThe Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz']
21-Feb-2017 13:35:31 - DEBUG   :: Thread-14 : [META-TAGGER] Absolute path to script: c:\Python27\python.exe
21-Feb-2017 13:35:34 - INFO    :: Thread-14 : [META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging [C:\Mylar\cache\mylar_7gyowx\Error deleting original RAR after export

The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz]
21-Feb-2017 13:35:34 - INFO    :: Thread-14 : [POST-PROCESSING] Sucessfully wrote metadata to .cbz (Error deleting original RAR after export

The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz) - Continuing..
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING] ofilename:Error deleting original RAR after export

The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING] odir: C:\Mylar\cache\mylar_7gyowx
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING] ofilename: Error deleting original RAR after export

The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING] ext:.cbz
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING] Original Filename: Error deleting original RAR after export

The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING] Original Extension: .cbz
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING] New Filename: The Punisher 8 (2017)
21-Feb-2017 13:35:34 - INFO    :: Thread-14 : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: D:\Media\Books\Comics\The Punisher (2016)
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING] Source: C:\Mylar\cache\mylar_7gyowx\Error deleting original RAR after export

The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING] Destination: D:\Media\Books\Comics\The Punisher (2016)\The Punisher 8 (2017).cbz
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING] Renaming C:\Mylar\cache\mylar_7gyowx\Error deleting original RAR after export

The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING] odir src : C:\Mylar\cache\mylar_7gyowx\Error deleting original RAR after export

The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING][move] C:\Mylar\cache\mylar_7gyowx\Error deleting original RAR after export

The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz ... to ... D:\Media\Books\Comics\The Punisher (2016)\The Punisher 8 (2017).cbz
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING] Failed to move C:\Mylar\cache\mylar_7gyowx\Error deleting original RAR after export

The Punisher 008 (2016) (Digital) (BlackManta-Empire).cbz - check directories and manually re-run.
21-Feb-2017 13:35:34 - DEBUG   :: Thread-14 : [POST-PROCESSING] Post-Processing ABORTED.
21-Feb-2017 13:35:34 - INFO    :: Thread-14 : [POST-PROCESSING] Manual post-processing completed for 1 issues.

**Comment by evilhero** [comment]
Wow ok that's not good - CT is causing some weird error thats appendix to the filename and it's screwing everything up thereafter. 

Did you happen to restart mylar after you made the config change to enable metadata? 

I haven't come across this, like ever so this is a new one. I have a weird feeling it's to do with perms or something as it's failing to delete it initially that's causing the problems. 

How are you starting mylar and can you confirm that the perms are indeed allowed for the program in the cache dir?

**Comment by Gamer106** [comment]
I have restarted after making changes, and I start it with net start. I'll check the permissions on the Mylar and enclosed folders.

**Comment by Gamer106** [comment]
Changed permissions so all have Full Control, started Mylar with Python on command prompt, same thing : /

**Comment by evilhero** [comment]
What are the perms on any of the mylar_xxx sub dirs within the cache folder, and are the cbr/cbz files within set the same?

**Comment by Gamer106** [comment]
I changed ownership of the folder and all enclosed to a particular user. That didn't resolve the issue, so I went back to ownership under Administrator which I am, and the only account. Anytime a new folder was created for post processing, it was under ownership of Administrator anyway.

**Comment by Gamer106** [comment]
Funny enough, comics downloaded with SAB are able to convert and remove the cache. Only torrents that are post processed aren't working. It also looks like running a manual post process fails the same way Torrents do.

**Comment by evilhero** [comment]
It's weird, but expected in a way - torrents do a manual post-processing, whereas sab does a different routine within mylar when post-processing. However both call the same delete function, but that's not the real problem here. 

It's the fact that it can't delete the rar initially that's causing the problem, even weirder by it being just manual post-processing from the cache. 

Can you paste in a screenie of your permissions for the cache directory? And what the permissions are for a cbr within a metatagging directory in the cache folder (the mylar_xxx folders). 

I have run mylar on win10x64, and  haven't had any issues with post-processing, metatagging and cleanup in the latest builds, so it looks like it's isolated to your install and that usually points to permissions of some kind.

**Comment by Gamer106** [comment]
<a href="https://ibb.co/msDxbF"><img src="https://thumb.ibb.co/msDxbF/IMG_1224.png" alt="IMG_1224" border="0"></a>

**Comment by Gamer106** [comment]
I don't know if an update or a permissions thing resolved it, but it's fixed!

**Comment by jimbojnr81** [comment]
I'm having this same issue with some, not all, torrent downloaded comics and anything bulk downloaded, ie compressed and in cbr format. I get pretty much the same error message

2017-08-24 09:02:23 | INFO | [META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging [C:\Users\Jimmy\Documents\mylar\cache/mylar_v_dyd2\Error deleting original RAR after export Batman Shadow of the Bat 000 (1994-10).cbz]
-- | -- | --
2017-08-24 09:02:23 | INFO | [META-TAGGER] ComicRack tagging meta-tagging processing started.
2017-08-24 09:02:21 | INFO | Attempting to move: move
2017-08-24 09:02:21 | INFO | New_Filepath: C:\Users\Jimmy\Documents\mylar\cache/mylar_v_dyd2\Batman Shadow of the Bat 000 (1994-10).cbr
2017-08-24 09:02:21 | INFO | New_Folder: C:\Users\Jimmy\Documents\mylar\cache/mylar_v_dyd2
2017-08-24 09:02:21 | INFO | Filename: Batman Shadow of the Bat 000 (1994-10).cbr
2017-08-24 09:02:21 | INFO | Filepath: D:\Comics\DC Comics\Batman Shadow of the Bat (V1992)\Batman Shadow of the Bat 000 (1994-10).cbr

I was getting this error for a while and then did a complete fresh install but still get the same error.

Full read write permissions have been given. I'm not sure what else to do. It's affecting only the cbr 
 files which are only 1 out of 5 downloaded and if I've bulk downloaded comics.

**Comment by evilhero** [comment]
Something is seriously messing up on Windows installs for some reason all of a sudden - you can tell because it's trying to delete the file `C:\Users\Jimmy\Documents\mylar\cache/mylar_v_dyd2\Error deleting original RAR after export Batman Shadow of the Bat 000 (1994-10).cbz`, which obviously doesn't exist (pay no mind to the wrong slash in the path, the orginal issue opener posted a simliar logline with the correct slashes). 

I'm thinking at this point it might be due to some weird locking - as CT has to unrar the contents of the cbr, then compress up the files into a cbz, and then remove both the cbr and all the jpg files it extracted previously. I'm thinking like this because windows is notorious for locking stuff during usage and not releasing it, whereas other systems don't exhibit this behaviour. So either I can try to capture the error, proceed and after the process has completed, try to delete the cache folder containing the cbr to be deleted (after the cbz has been moved to the new location).

I'll have to look into this as this is abit perplexing (especially since I haven't seen it on linux, so I'll have to load up a windows machine and do some spot checking)...

**Comment by evilhero** [comment]
Think I have this fixed in my local repo - need to do abit more cleanup/test against it, but based on the errors I've seen thus far it should fix the problem (instead of deleting it after the initial conversion, it will wait until the entire tagging is finished and then delete the cache folder itself as the last step in the post-processing flow)

**Comment by jimbojnr81** [comment]
Sorry to be a pain, do you know when you'll be pushing the above fix out? Happy to help be a guinea pig for your fix.

**Comment by evilhero** [comment]
It should be fixed now in one of the dev commits that got pushed yesterday. Make sure you're up to date on dev, and then try again.. If it doesnt work, please let me know (debug logs help alot too)

**Comment by jimbojnr81** [comment]
I've updated Mylar to the latest commit and have run a manual metatag and im still getting the same error message

2017-09-19 17:01:54 | INFO | [META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging [C:\Users\Jimmy\Documents\mylar\cache/mylar_lvowc4\Error deleting original RAR after export Batman Shadow of the Bat 021 (1993-10).cbz]
-- | -- | --
2017-09-19 17:01:54 | DEBUG | [META-TAGGER] Absolute path to script: C:\Python27\python.exe
2017-09-19 17:01:54 | DEBUG | [META-TAGGER] Executing command: ['C:\\Python27\\python.exe', 'C:\\Users\\Jimmy\\Documents\\mylar\\comictagger.py', '-s', '-m', 'volume=1', '--cv-api-key', u'REDACTED', '-o', '--id', u'38160', '--type', 'cr', u'C:\\Users\\Jimmy\\Documents\\mylar\\cache/mylar_lvowc4\\Error deleting original RAR after export\r\nBatman Shadow of the Bat 021 (1993-10).cbz']
2017-09-19 17:01:54 | DEBUG | [META-TAGGER] Enabling ComicTagger script: ['C:\\Python27\\python.exe', 'C:\\Users\\Jimmy\\Documents\\mylar\\comictagger.py'] with options: ['-s', '-m', 'volume=1', '--cv-api-key', u'REDACTED', '-o', '--id', u'38160', '--type', 'cr', u'C:\\Users\\Jimmy\\Documents\\mylar\\cache/mylar_lvowc4\\Error deleting original RAR after export\r\nBatman Shadow of the Bat 021 (1993-10).cbz']
2017-09-19 17:01:54 | INFO | [META-TAGGER] ComicRack tagging meta-tagging processing started.
2017-09-19 17:01:54 | DEBUG | [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] New filename: C:\Users\Jimmy\Documents\mylar\cache/mylar_lvowc4\Error deleting original RAR after export Batman Shadow of the Bat 021 (1993-10).cbz
2017-09-19 17:01:54 | DEBUG | [META-TAGGER]Trying latin-1 conversion.
2017-09-19 17:01:54 | DEBUG | [META-TAGGER]Trying utf-8 conversion.
2017-09-19 17:01:54 | DEBUG | [META-TAGGER][COMIC-TAGGER] : Error deleting original RAR after export Archive exported successfully to: Batman Shadow of the Bat 021 (1993-10).cbz
2017-09-19 17:01:53 | DEBUG | [META-TAGGER] Absolute path to script: C:\Python27\python.exe
2017-09-19 17:01:53 | DEBUG | [META-TAGGER] Executing command: ['C:\\Python27\\python.exe', 'C:\\Users\\Jimmy\\Documents\\mylar\\comictagger.py', '-e', '--delete-rar', u'C:\\Users\\Jimmy\\Documents\\mylar\\cache/mylar_lvowc4\\Batman Shadow of the Bat 021 (1993-10).cbr']
2017-09-19 17:01:53 | DEBUG | [META-TAGGER] Enabling ComicTagger script: ['C:\\Python27\\python.exe', 'C:\\Users\\Jimmy\\Documents\\mylar\\comictagger.py'] with options: ['-e', '--delete-rar', u'C:\\Users\\Jimmy\\Documents\\mylar\\cache/mylar_lvowc4\\Batman Shadow of the Bat 021 (1993-10).cbr']
2017-09-19 17:01:53 | DEBUG | [META-TAGGER] CR Tagging enabled.
2017-09-19 17:01:53 | DEBUG | [META-TAGGER] ComicTagger 1.20.1 [ninjas.walk.alone / SHURIKEN] being used - using personal ComicVine API key supplied via mylar.
2017-09-19 17:01:53 | DEBUG | [META-TAGGER] Running the ComicTagger Add-on for Mylar
2017-09-19 17:01:53 | DEBUG | [META-TAGGER] comicpath : C:\Users\Jimmy\Documents\mylar\cache/mylar_lvowc4
2017-09-19 17:01:53 | DEBUG | [META-TAGGER] sabnzbdscriptpath : C:\Users\Jimmy\Documents\mylar
2017-09-19 17:01:53 | DEBUG | [META-TAGGER] downloadpath : D:\Comics\DC Comics\Batman Shadow of the Bat (V1992)
2017-09-19 17:01:53 | DEBUG | [META-TAGGER] scriptname : Mylar.py
2017-09-19 17:01:53 | DEBUG | [META-TAGGER] Paths / Locations:
2017-09-19 17:01:52 | INFO | Attempting to move: move
2017-09-19 17:01:52 | INFO | New_Filepath: C:\Users\Jimmy\Documents\mylar\cache/mylar_lvowc4\Batman Shadow of the Bat 021 (1993-10).cbr
2017-09-19 17:01:52 | INFO | New_Folder: C:\Users\Jimmy\Documents\mylar\cache/mylar_lvowc4
2017-09-19 17:01:52 | INFO | Filename: Batman Shadow of the Bat 021 (1993-10).cbr
2017-09-19 17:01:52 | INFO | Filepath: D:\Comics\DC Comics\Batman Shadow of the Bat (V1992)\Batman Shadow of the Bat 021 (1993-10).cbr
2017-09-19 17:01:52 | DEBUG | [META-TAGGER] Filename is : D:\Comics\DC Comics\Batman Shadow of the Bat (V1992)\Batman Shadow of the Bat 021 (1993-10).cbr
2017-09-19 17:01:52 | DEBUG | ComicTagger Path location for internal comictagger.py set to : C:\Users\Jimmy\Documents\mylar\comictagger.py
2017-09-19 17:01:52 | DEBUG | [META-TAGGER] dirName:D:\Comics\DC Comics\Batman Shadow of the Bat (V1992)
2017-09-19 17:01:42 | DEBUG | If you read this message, debug logging is available
2017-09-19 17:01:42 | INFO | Verbose toggled, set to True
