### ISSUE TITLE
Error on Search/ComicVine

### ISSUE THREAD

**Issue by jbondsr** [evilhero/mylar#1610]
Recently, cannot do a search.

Unable to perform required pull-list search for : [xxxxxxx]

Error fetching data from ComicVine: [Errno 1] _ssl.c:499: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

**Comment by evilhero** [comment]
Is your python at the required level of at least 2.7.9?

**Comment by dudeslife** [comment]
jbondsr

if you are on 14.04 and don't want to update your ubu, here is the solution.

sudo add-apt-repository ppa:fkrull/deadsnakes-python2.7
sudo apt-get update
sudo apt-get install python2.7
python --version

**Comment by evilhero** [comment]
There's also the wonderful pyenv - which let's you run multiple python versions simultaneously without ever touching your main OS python, so as to not screw up your OS. 

@dudeslife (thanks for the input!) gave another easy way - just make sure you don't uninstall your original python ;)

**Comment by dudeslife** [comment]
@evilhero 

this may or not be related, but I am getting a strange error now.

Error fetching data from Myindexer(newznab) [RSS]: __str__ returned non-string (type Error)

**Comment by jbondsr** [comment]
Thanks. It is fixed. I updated to python 2.7.9. I should have done a search before bothering the forum. Sorry guys and thanks. I have another issue where the status continually shows as a spinning circle, but I will do some reasearch before I post again.

**Comment by castertr0y357** [comment]
I still see this problem, and the python version I'm running is 2.7.9.  This is running in a freenas jail.

Debug logging doesn't show anything additional.

Here is what I see in the logs:

`2017-05-03 22:32:37	ERROR	Uncaught exception: Traceback (most recent call last):
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/pbi/mylar-amd64/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/importer.py", line 101, in addComictoDB
comic = cv.getComic(comicid, 'comic')
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/cv.py", line 156, in getComic
return GetComicInfo(comicid, dom)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/cv.py", line 220, in GetComicInfo
tracks = dom.getElementsByTagName('issue')
AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'

2017-05-03 22:32:37	WARNING	Error fetching data from ComicVine: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

2017-05-03 22:32:35	INFO	Attempting to add directly by ComicVineID: 83480`

Not sure what I'm missing. :(

**Comment by evilhero** [comment]
Cv switched to https only recently, so if it can't verify the certificate it will throw that error. At that point it's up to the client machine to be able to verify the certificate. Yours isn't able to because either your pyopenssl isn't of high enough level or your missing something important in that regards from your system. 

Usually if you can do a ```pip install requests[cryptography] ``` it will get things working for you, but failing that you'd need to figure out what on your system is needed to get updated (pyopenssl or even openssl).
