### ISSUE TITLE
Metadata tagging not working

### ISSUE THREAD

**Issue by Baldrdk** [evilhero/mylar#1681]
Meta taggin worked until recently. But now not so much.

When i enable metadata tagging i get the message.
[META-TAGGER][WARNING] Make sure that you are using the comictagger included with Mylar.

When mylar try to import and meta tag, I get the error

Uncaught exception: Traceback (most recent call last):File "C:\ProgramData\mylar\mylar\logger.py", line 158, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "C:\ProgramData\mylar\mylar\PostProcessor.py", line 1248, in Processself.Process_next(comicid, issueid, issuenumOG, ml, stat)File "C:\ProgramData\mylar\mylar\PostProcessor.py", line 1634, in Process_nextpcheck = cmtagmylar.run(self.nzb_folder, issueid=issueid, comversion=vol_label, manual="yes", filename=ml['ComicLocation'])File "C:\ProgramData\mylar\mylar\cmtagmylar.py", line 110, in runtidyup(filepath, new_filepath, new_folder)File "C:\ProgramData\mylar\mylar\cmtagmylar.py", line 258, in tidyupshutil.remove(new_folder)AttributeError: 'module' object has no attribute 'remove'
--
2017-07-17 10:57:51 | WARNING | [META-TAGGER][WARNING] Make sure that you are using the comictagger included with Mylar.
2017-07-17 10:57:50 | INFO | Attempting to move: move
2017-07-17 10:57:49 | INFO | New_Filepath: C:\ProgramData\mylar\cache/mylar_sw_cb3\*** 000 (2012) (Digital) (Nahga-Empire).cbr
2017-07-17 10:57:49 | INFO | New_Folder: C:\ProgramData\mylar\cache/mylar_sw_cb3
2017-07-17 10:57:49 | INFO | Filename: Green Lantern Corps 000 (2012) (Digital) (Nahga-Empire).cbr
2017-07-17 10:57:49 | INFO | Filepath: ****
2017-07-17 10:57:49 | INFO | [POST-PROCESSING] [1/85] Starting Post-Processing for ***

**Comment by evilhero** [comment]
Came across this the other day myself, not sure how it snuck that far in without anyone else noticing - but I have a fix waiting to go. Just need to get to a machine to commit it up (later today at the latest)

**Comment by evilhero** [comment]
This should be fixed in the latest commit in development now - 906f2b1 ( I just forgot to tag it to the commit as I pushed it out from another device)

**Comment by claym** [comment]
Not sure if this is the exact same issue, but here's what post processing looked like for after updating:


```
2017-07-26 17:32:43 | WARNING | [POST-PROCESSING] Post-Processing ABORTED
-- | -- | --
2017-07-26 17:32:43 | WARNING | [POST-PROCESSING] Failed to move /usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV/Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbz - check directories and manually re-run.
2017-07-26 17:32:43 | DEBUG | [POST-PROCESSING] Renaming /usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV/Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbz ..to.. /usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV/Crosswind (2017) 001.cbz
2017-07-26 17:32:43 | DEBUG | [POST-PROCESSING] nfilename:Crosswind (2017) 001.cbz
2017-07-26 17:32:43 | DEBUG | [POST-PROCESSING] ofilename:Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbz
2017-07-26 17:32:43 | DEBUG | [POST-PROCESSING] odir: /usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV
2017-07-26 17:32:43 | DEBUG | [POST-PROCESSING] self.nzb_folder: /mnt/media/download/sabnzbd/complete/comics/Crosswind.001.2017.Digital.Mephisto-Empire.1
2017-07-26 17:32:43 | DEBUG | [POST-PROCESSING] Destination: /mnt/media/comics/library/Image/Crosswind (2017)/Crosswind (2017) 001.cbz
2017-07-26 17:32:43 | DEBUG | [POST-PROCESSING] Source: /usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV/Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbz
2017-07-26 17:32:43 | INFO | [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /mnt/media/comics/library/Image/Crosswind (2017)
2017-07-26 17:32:43 | DEBUG | [POST-PROCESSING] New Filename: Crosswind (2017) 001
2017-07-26 17:32:43 | DEBUG | [POST-PROCESSING] Original Extension: .cbz
2017-07-26 17:32:43 | DEBUG | [POST-PROCESSING] Original Filename: Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbz
2017-07-26 17:32:43 | INFO | [POST-PROCESSING] Sucessfully wrote metadata to .cbz (Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbz) - Continuing..
2017-07-26 17:32:43 | INFO | [META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging [/usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV/Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbz]
2017-07-26 17:32:39 | DEBUG | [META-TAGGER] Absolute path to script: /usr/pbi/mylar-amd64/bin/python2.7
2017-07-26 17:32:39 | DEBUG | [META-TAGGER] Executing command: ['/usr/pbi/mylar-amd64/bin/python2.7', '/usr/pbi/mylar-amd64/share/mylar/mylar/comictagger.py', '-s', '-m', 'volume=1', '--cv-api-key', u'REDACTED', '-o', '--id', u'603157', '--type', 'cr', u'/usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV/Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbz']
2017-07-26 17:32:39 | DEBUG | [META-TAGGER] Enabling ComicTagger script: ['/usr/pbi/mylar-amd64/bin/python2.7', '/usr/pbi/mylar-amd64/share/mylar/mylar/comictagger.py'] with options: ['-s', '-m', 'volume=1', '--cv-api-key', u'REDACTED', '-o', '--id', u'603157', '--type', 'cr', u'/usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV/Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbz']
2017-07-26 17:32:39 | INFO | [META-TAGGER] ComicRack tagging meta-tagging processing started.
2017-07-26 17:32:39 | DEBUG | [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] New filename: /usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV/Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbz
2017-07-26 17:32:39 | DEBUG | [META-TAGGER][COMIC-TAGGER] : Archive exported successfully to: Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbz (Original deleted)
2017-07-26 17:32:22 | DEBUG | [META-TAGGER] Absolute path to script: /usr/pbi/mylar-amd64/bin/python2.7
2017-07-26 17:32:22 | DEBUG | [META-TAGGER] Executing command: ['/usr/pbi/mylar-amd64/bin/python2.7', '/usr/pbi/mylar-amd64/share/mylar/mylar/comictagger.py', '-e', '--delete-rar', u'/usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV/Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbr']
2017-07-26 17:32:22 | DEBUG | [META-TAGGER] Enabling ComicTagger script: ['/usr/pbi/mylar-amd64/bin/python2.7', '/usr/pbi/mylar-amd64/share/mylar/mylar/comictagger.py'] with options: ['-e', '--delete-rar', u'/usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV/Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbr']
2017-07-26 17:32:22 | DEBUG | [META-TAGGER] CR Tagging enabled.
2017-07-26 17:32:22 | DEBUG | [META-TAGGER] ComicTagger 1.20.1 [ninjas.walk.alone / SHURIKEN] being used - using personal ComicVine API key supplied via mylar.
2017-07-26 17:32:21 | DEBUG | [META-TAGGER] Running the ComicTagger Add-on for Mylar
2017-07-26 17:32:21 | DEBUG | [META-TAGGER] comicpath : /usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV
2017-07-26 17:32:21 | DEBUG | [META-TAGGER] sabnzbdscriptpath : /usr/pbi/mylar-amd64/share/mylar/mylar
2017-07-26 17:32:21 | DEBUG | [META-TAGGER] downloadpath : /mnt/media/download/sabnzbd/complete/comics/Crosswind.001.2017.Digital.Mephisto-Empire.1
2017-07-26 17:32:21 | DEBUG | [META-TAGGER] scriptname : Mylar.py
2017-07-26 17:32:21 | DEBUG | [META-TAGGER] Paths / Locations:
2017-07-26 17:32:21 | INFO | Attempting to move: move
2017-07-26 17:32:21 | INFO | New_Filepath: /usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV/Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbr
2017-07-26 17:32:21 | INFO | New_Folder: /usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV
2017-07-26 17:32:21 | INFO | Filename: Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbr
2017-07-26 17:32:21 | INFO | Filepath: /mnt/media/download/sabnzbd/complete/comics/Crosswind.001.2017.Digital.Mephisto-Empire.1/Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbr
2017-07-26 17:32:21 | DEBUG | [META-TAGGER] Filename is : /mnt/media/download/sabnzbd/complete/comics/Crosswind.001.2017.Digital.Mephisto-Empire.1/Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbr
2017-07-26 17:32:21 | DEBUG | ComicTagger Path location for internal comictagger.py set to : /usr/pbi/mylar-amd64/share/mylar/mylar/comictagger.py
2017-07-26 17:32:21 | DEBUG | [META-TAGGER] dirName:/mnt/media/download/sabnzbd/complete/comics/Crosswind.001.2017.Digital.Mephisto-Empire.1
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] Metatagging enabled - proceeding...
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] ofilename: Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbr
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] odir: /mnt/media/download/sabnzbd/complete/comics/Crosswind.001.2017.Digital.Mephisto-Empire.1
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] ofilename: Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbr
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] odir (root): /mnt/media/download/sabnzbd/complete/comics/Crosswind.001.2017.Digital.Mephisto-Empire.1
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] New format: $Series ($Year) $Issue
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] Not an annual - removing from filename parameters
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] New format is now: $Series ($Year) $Issue
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] No version # found for series, removing from filename
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] Comic Version: None
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] Comic Location: /mnt/media/comics/library/Image/Crosswind (2017)
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] Year: 2017
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] Series: Crosswind
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] Publisher: Image
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] Issue Year : 2017
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] Pretty Comic Issue is : 001
2017-07-26 17:32:21 | DEBUG | Zero level supplement set to 00x. Issue will be set as : 001
2017-07-26 17:32:21 | DEBUG | issue detected less than 10
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] Zero Suppression set to : 00x
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] issuenumOG: 1
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] issueid: 603157
2017-07-26 17:32:21 | INFO | [POST-PROCESSING] [1/1] Starting Post-Processing for Crosswind issue: 1
2017-07-26 17:32:21 | INFO | [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
2017-07-26 17:32:21 | INFO | [DUPECHECK] Duplicate check for /mnt/media/download/sabnzbd/complete/comics/Crosswind.001.2017.Digital.Mephisto-Empire.1
2017-07-26 17:32:21 | INFO | [POST-PROCESSING] issuenzb found.
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] Issueid: 603157
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] After conversions, nzbname is : Crosswind.001.2017.Digital.Mephisto-Empire
2017-07-26 17:32:21 | DEBUG | [NZBNAME] nzbname (remove extensions, double spaces, convert underscores to spaces): Crosswind 001 2017 Digital Mephisto-Empire
2017-07-26 17:32:21 | DEBUG | [NZBNAME] nzbname (remove chars): Crosswind.001.2017.Digital.Mephisto-Empire
2017-07-26 17:32:21 | DEBUG | [NZBNAME]: Crosswind.001.2017.Digital.Mephisto-Empire
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] nzb folder: /mnt/media/download/sabnzbd/complete/comics/Crosswind.001.2017.Digital.Mephisto-Empire.1
2017-07-26 17:32:21 | DEBUG | [POST-PROCESSING] nzb name: Crosswind.001.2017.Digital.Mephisto-Empire
2017-07-26 17:32:21 | INFO | Starting postprocessing for : Crosswind.001.2017.Digital.Mephisto-Empire
2017-07-26 17:32:21 | WARNING | ComicRN should be v1.01 and autoProcessComics.py should be v1.0, but they are not and are out of date. Post-Processing may or may not work.
2017-07-26 17:32:02 | INFO | [UPDATER] Updated the status (Snatched) complete for Crosswind Issue: 1


```

**Comment by evilhero** [comment]
@claym : that looks like a permissions issue of some kind. It tags, renames the file (it should be in the cache/mylar_xxxxx folder still probably), but then fails to move it from the cache location to your series location. Make sure the user running mylar has full rights to both directories. 

I also see the /usr/pbi.... sequence in your path and think that you installed Mylar other than git/source,  which can enforce permissions that goes against what Mylar requires to run (it's come up several times before)

**Comment by claym** [comment]
ahhaha, well I think my permissions are set up correctly (and it's actually pulled from github)- it would have to be to even create the mylar_xxxxx directory.

```
root@blackbeard:/usr/pbi/mylar-amd64/share/mylar/mylar/cache/mylar_RZ3HUV # ls -al
total 37310
drwx------   2 media  media         3 Jul 26 17:32 .
drwxrwxr-x  32 media  media       334 Jul 26 17:32 ..
-rw-------   1 media  media  37869529 Jul 26 17:32 Crosswind 001 (2017) (Digital) (Mephisto-Empire).cbz
```

we should probably move this to it's own issue :)

**Comment by evilhero** [comment]
I can't move the posts under your nick (github stuff) - if you recreate an issue with both your comments we can converse more and there and I'll close this one up then (and delete your comments cause they'll be in the other thread).

A few quick questions in the meantime:
- The file has a 600 permission - is that supposed to be present ? 
- Do you use the ownership settings with Mylar for owner:group / permissions and if you do what are they set to ? 
- Is the user running Mylar in the media group or the media user ? 
- Did the move complete properly (it copies it first, then deletes thereafter) into the correct series directory but then possibly failed on doing something else thereafter ?

**Comment by Baldrdk** [comment]
I updated to development build, but i am still getting the same error.

Mylar Version: development
-- source build 906f2b1479671a03b96817d491d34d976c373948.
Python Version : 2.7.10

**Comment by evilhero** [comment]
@Baldrdk : If you're running the latest development branch, then that error wouldn't be appearing since that command no longer exists as per the log you posted earlier. 

Shutdown Mylar, delete all the .pyc files in the mylar subdirectory, start up Mylar and try again. If you receive an error message, please post it in here with the leading debug log lines so that I can see what it is that's happening.

**Comment by Baldrdk** [comment]
ok at at closer look it might not be the same error. This is what the log says:


2017-07-28 11:01:02 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\ProgramData\mylar\mylar\logger.py", line 165, in new_runold_run(*args, **kwargs)File "C:\Python27\lib\threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "C:\ProgramData\mylar\mylar\PostProcessor.py", line 797, in Processmetaresponse = cmtagmylar.run(self.nzb_folder, issueid=issueid, filename=ofilename)File "C:\ProgramData\mylar\mylar\cmtagmylar.py", line 110, in runtidyup(filepath, new_filepath, new_folder)File "C:\ProgramData\mylar\mylar\cmtagmylar.py", line 266, in tidyupif mylar.FILE_OPTS == 'copy' and manualmeta == False:NameError: global name 'manualmeta' is not defined
-- | -- | --
2017-07-28 11:01:02 | WARNING | [META-TAGGER][WARNING] Make sure that you are using the comictagger included with Mylar.

**Comment by evilhero** [comment]
Yep - different error. Should be fixed now in the latest development commit. Thanks for the detailed log info ;)

**Comment by Baldrdk** [comment]
Updated to latest developer release.
It still wont write the metatag. Now it looks like some permission error for the temp dir. I havnt change anyting.

log:
29-jul-2017 12:41:22 - WARNING :: CP Server Thread-9 : [META-TAGGER] Unexpected Error: <type 'exceptions.IOError'>
29-jul-2017 12:41:22 - WARNING :: CP Server Thread-9 : [META-TAGGER] Unable to create temporary directory to perform meta-tagging. Processing without metatagging.
29-jul-2017 12:41:22 - DEBUG   :: CP Server Thread-9 : [MANUAL META-TAGGING] Unable to write metadata successfully - check mylar.log file.
29-jul-2017 12:41:22 - DEBUG   :: CP Server Thread-9 : [META-TAGGER] dirName:D:\Media\Comics\DC Comics/Batman Beyond/Batman Beyond (2016)
29-jul-2017 12:41:22 - DEBUG   :: CP Server Thread-9 : ComicTagger Path location for internal comictagger.py set to : C:\ProgramData\mylar\comictagger.py
29-jul-2017 12:41:22 - DEBUG   :: CP Server Thread-9 : [META-TAGGER] Filename is : D:\Media\Comics\DC Comics/Batman Beyond/Batman Beyond (2016)\Batman Beyond v6 009 (08 2017).cbr
29-jul-2017 12:41:22 - INFO    :: CP Server Thread-9 : Filepath: D:\Media\Comics\DC Comics/Batman Beyond/Batman Beyond (2016)\Batman Beyond v6 009 (08 2017).cbr
29-jul-2017 12:41:22 - INFO    :: CP Server Thread-9 : Filename: Batman Beyond v6 009 (08 2017).cbr
29-jul-2017 12:41:22 - INFO    :: CP Server Thread-9 : New_Folder: C:\ProgramData\mylar\cache/mylar_fqpqob
29-jul-2017 12:41:22 - INFO    :: CP Server Thread-9 : New_Filepath: C:\ProgramData\mylar\cache/mylar_fqpqob\Batman Beyond v6 009 (08 2017).cbr
29-jul-2017 12:41:22 - INFO    :: CP Server Thread-9 : Attempting to move: copy
29-jul-2017 12:41:22 - WARNING :: CP Server Thread-9 : [META-TAGGER] Unexpected Error: <type 'exceptions.IOError'>
29-jul-2017 12:41:22 - WARNING :: CP Server Thread-9 : [META-TAGGER] Unable to create temporary directory to perform meta-tagging. Processing without metatagging.
29-jul-2017 12:41:22 - DEBUG   :: CP Server Thread-9 : [MANUAL META-TAGGING] Unable to write metadata successfully - check mylar.log file.
29-jul-2017 12:41:22 - DEBUG   :: CP Server Thread-9 : [META-TAGGER] dirName:D:\Media\Comics\DC Comics/Batman Beyond/Batman Beyond (2016)
29-jul-2017 12:41:22 - DEBUG   :: CP Server Thread-9 : ComicTagger Path location for internal comictagger.py set to : C:\ProgramData\mylar\comictagger.py
29-jul-2017 12:41:22 - DEBUG   :: CP Server Thread-9 : [META-TAGGER] Filename is : D:\Media\Comics\DC Comics/Batman Beyond/Batman Beyond (2016)\Batman Beyond v6 010 (09 2017).cbr
29-jul-2017 12:41:22 - INFO    :: CP Server Thread-9 : Filepath: D:\Media\Comics\DC Comics/Batman Beyond/Batman Beyond (2016)\Batman Beyond v6 010 (09 2017).cbr
29-jul-2017 12:41:22 - INFO    :: CP Server Thread-9 : Filename: Batman Beyond v6 010 (09 2017).cbr
29-jul-2017 12:41:22 - INFO    :: CP Server Thread-9 : New_Folder: C:\ProgramData\mylar\cache/mylar_vds7k1
29-jul-2017 12:41:22 - INFO    :: CP Server Thread-9 : New_Filepath: C:\ProgramData\mylar\cache/mylar_vds7k1\Batman Beyond v6 010 (09 2017).cbr
29-jul-2017 12:41:22 - INFO    :: CP Server Thread-9 : Attempting to move: copy
29-jul-2017 12:41:22 - WARNING :: CP Server Thread-9 : [META-TAGGER] Unexpected Error: <type 'exceptions.IOError'>
29-jul-2017 12:41:22 - WARNING :: CP Server Thread-9 : [META-TAGGER] Unable to create temporary directory to perform meta-tagging. Processing without metatagging.
29-jul-2017 12:41:22 - DEBUG   :: CP Server Thread-9 : [MANUAL META-TAGGING] Unable to write metadata successfully - check mylar.log file.
29-jul-2017 12:41:22 - INFO    :: CP Server Thread-9 : [SERIES-METATAGGER][Batman Beyond (2016)] Finished doing a complete series (re)tagging of metadata.

**Comment by evilhero** [comment]
The IOError usually means that it can't locate the directory/file or the disk is full. Since it's erroring out on trying to create the temporary directory - make sure the path it's indicating exists, as well as the disk is not full.

Note the slashes you have in your cache path for some reason: `C:\ProgramData\mylar\cache/mylar_fqpqob\`, which to me would indicate that the `/` is being designated as a control character and being ignored entirely as part of the path.

**Comment by Baldrdk** [comment]
I tried with a completely new install of the devolpment branch. 
Still getting the warning to use the meta-tagger included in mylar. And still not writing metadata.
log says 
29-jul-2017 20:38:22 - WARNING :: Thread-14 : [META-TAGGER][WARNING] Make sure that you are using the comictagger included with Mylar.

full log
29-jul-2017 20:38:20 - INFO    :: Thread-14 : [POST-PROCESSING] [1/1] Starting Post-Processing for X-Men: Blue issue: 7
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] issueid: 608266
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] issuenumOG: 7
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] Zero Suppression set to : none
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : issue detected less than 10
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : Zero level supplement set to none. Issue will be set as : 7
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] Pretty Comic Issue is : 7
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] Issue Year : 2017
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] Publisher: Marvel
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] Series: X-Men: Blue
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] Year: 2017
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] Comic Location: D:\temp\X-Men Blue (2017)
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] Comic Version: None
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] No version # found for series, removing from filename
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] New format is now: $Series $Issue ($Year)
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] Not an annual - removing from filename parameters
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] New format: $Series $Issue ($Year)
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [POST-PROCESSING] Metatagging enabled - proceeding...
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [META-TAGGER] dirName:D:\Peer2Peer\_Dropbox\_comics
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : ComicTagger Path location for internal comictagger.py set to : C:\mylar-development\comictagger.py
29-jul-2017 20:38:20 - DEBUG   :: Thread-14 : [META-TAGGER] Filename is : D:\Peer2Peer\_Dropbox\_comics\X-Men Blue 007 (2017) (Digital) (Zone-Empire).cbr
29-jul-2017 20:38:20 - INFO    :: Thread-14 : Filepath: D:\Peer2Peer\_Dropbox\_comics\X-Men Blue 007 (2017) (Digital) (Zone-Empire).cbr
29-jul-2017 20:38:20 - INFO    :: Thread-14 : Filename: X-Men Blue 007 (2017) (Digital) (Zone-Empire).cbr
29-jul-2017 20:38:20 - INFO    :: Thread-14 : New_Folder: C:\mylar-development\cache\mylar_ukuara
29-jul-2017 20:38:20 - INFO    :: Thread-14 : New_Filepath: C:\mylar-development\cache\mylar_ukuara\X-Men Blue 007 (2017) (Digital) (Zone-Empire).cbr
29-jul-2017 20:38:20 - INFO    :: Thread-14 : Attempting to copy: copy
29-jul-2017 20:38:21 - DEBUG   :: Thread-14 : [META-TAGGER] Paths / Locations:
29-jul-2017 20:38:21 - DEBUG   :: Thread-14 : [META-TAGGER] scriptname : Mylar.py
29-jul-2017 20:38:21 - DEBUG   :: Thread-14 : [META-TAGGER] downloadpath : D:\Peer2Peer\_Dropbox\_comics
29-jul-2017 20:38:21 - DEBUG   :: Thread-14 : [META-TAGGER] sabnzbdscriptpath : C:\mylar-development
29-jul-2017 20:38:21 - DEBUG   :: Thread-14 : [META-TAGGER] comicpath : C:\mylar-development\cache\mylar_ukuara
29-jul-2017 20:38:21 - DEBUG   :: Thread-14 : [META-TAGGER] Running the ComicTagger Add-on for Mylar
29-jul-2017 20:38:22 - WARNING :: Thread-14 : [META-TAGGER][WARNING] Make sure that you are using the comictagger included with Mylar.
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING] Unable to write metadata successfully - check mylar.log file. Attempting to continue without tagging...
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING] ofilename:X-Men Blue 007 (2017) (Digital) (Zone-Empire).cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING] odir: D:\Peer2Peer\_Dropbox\_comics
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING] ofilename: X-Men Blue 007 (2017) (Digital) (Zone-Empire).cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING] ext:.cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING] Original Filename: X-Men Blue 007 (2017) (Digital) (Zone-Empire).cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING] Original Extension: .cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING] New Filename: X-Men Blue 7 (2017)
29-jul-2017 20:38:22 - INFO    :: Thread-14 : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: D:\temp\X-Men Blue (2017)
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING] Source: D:\Peer2Peer\_Dropbox\_comics\X-Men Blue 007 (2017) (Digital) (Zone-Empire).cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING] Destination: D:\temp\X-Men Blue (2017)\X-Men Blue 7 (2017).cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING] Renaming D:\Peer2Peer\_Dropbox\_comics\X-Men Blue 007 (2017) (Digital) (Zone-Empire).cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING] odir src : D:\Peer2Peer\_Dropbox\_comics\X-Men Blue 007 (2017) (Digital) (Zone-Empire).cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][copy] D:\Peer2Peer\_Dropbox\_comics\X-Men Blue 007 (2017) (Digital) (Zone-Empire).cbr ... to ... D:\temp\X-Men Blue (2017)\X-Men Blue 7 (2017).cbr
29-jul-2017 20:38:22 - INFO    :: Thread-14 : [POST-PROCESSING] copy successful to : D:\temp\X-Men Blue (2017)\X-Men Blue 7 (2017).cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : File Option: copy [META-ENABLED: True]
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : odir: D:\Peer2Peer\_Dropbox\_comics [self.nzb_folder: D:\Peer2Peer\_Dropbox\_comics]
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][UPDATER] comicid: 100712
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][UPDATER] issueid: 608266
29-jul-2017 20:38:22 - INFO    :: Thread-14 : [POST-PROCESSING][UPDATER] Setting status to Post-Processed in history.
29-jul-2017 20:38:22 - INFO    :: Thread-14 : [POST-PROCESSING][UPDATER] Updating Status (Post-Processed) now complete for X-Men: Blue issue: 7
29-jul-2017 20:38:22 - INFO    :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] Now checking files for X-Men: Blue (2017) in D:\temp\X-Men Blue (2017)
29-jul-2017 20:38:22 - INFO    :: Thread-14 : there are 2 files.
29-jul-2017 20:38:22 - INFO    :: Thread-14 : [FILENAME]: X-Men Blue 7 (2017).cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : checking date : 2017
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : date: 2017
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : datecheck: [{'date': '2017', 'position': 3, 'mod_position': 13}]
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : sctd: 2017
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : year verified as : 2017
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : year verified as: 2017
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : highest_series_position: 3
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : possible_issuenumbers: [{'position': 2, 'validcountchk': False, 'number': '7', 'mod_position': 11}]
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : issue_position: 2
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : issue verified as : 7
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : series title possibly: X-Men Blue
29-jul-2017 20:38:22 - INFO    :: Thread-14 : Series_Name: X-Men Blue --- WatchComic: X-Men: Blue
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [MATCH: X-Men Blue] X-Men Blue 7 (2017).cbr
29-jul-2017 20:38:22 - INFO    :: Thread-14 : [FILENAME]: X-Men Blue 8 (2017).cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : checking date : 2017
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : date: 2017
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : datecheck: [{'date': '2017', 'position': 3, 'mod_position': 13}]
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : sctd: 2017
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : year verified as : 2017
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : year verified as: 2017
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : highest_series_position: 3
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : possible_issuenumbers: [{'position': 2, 'validcountchk': False, 'number': '8', 'mod_position': 11}]
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : issue_position: 2
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : issue verified as : 8
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : series title possibly: X-Men Blue
29-jul-2017 20:38:22 - INFO    :: Thread-14 : Series_Name: X-Men Blue --- WatchComic: X-Men: Blue
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : Possible Alternate Names to match against (if necessary): ['127372873872871091383 abdkhjhskjhkjdhakajhf']
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [MATCH: X-Men Blue] X-Men Blue 8 (2017).cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN]comiccnt is:2
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : No issues with identical issue numbering were detected for this series
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : mc_issue:[]
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : mc_annual:[]
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] temploc: 7
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] [608266] Issue match - fcdigit: 7000 ... int_iss: 7000
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] Matched...issue: X-Men: Blue#7 --- 7000
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] .......filename: X-Men Blue 7 (2017).cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] .......filesize: 95001888
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] temploc: 8
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] [610543] Issue match - fcdigit: 8000 ... int_iss: 8000
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] Matched...issue: X-Men: Blue#8 --- 8000
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] .......filename: X-Men Blue 8 (2017).cbr
29-jul-2017 20:38:22 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] .......filesize: 47438611
29-jul-2017 20:38:23 - INFO    :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] Updated the status of 6 issues for X-Men: Blue (2017) that were not found.
29-jul-2017 20:38:23 - INFO    :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] Total files located: 2
29-jul-2017 20:38:23 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] 0 issue(s) are in an Archive status already. Increasing Have total from 2 to include these archives.
29-jul-2017 20:38:23 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] I have changed the status of 0 issues to a status of Archived, as I now cannot locate them in the series directory.
29-jul-2017 20:38:23 - DEBUG   :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] Ensuring permissions/ownership enforced for series: X-Men: Blue
29-jul-2017 20:38:23 - INFO    :: Thread-14 : [POST-PROCESSING][FILE-RESCAN] I have physically found 2 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 2 / 8 ]
29-jul-2017 20:38:23 - INFO    :: Thread-14 : [POST-PROCESSING] Post-Processing completed for: X-Men: Blue issue: 7
29-jul-2017 20:38:23 - INFO    :: Thread-14 : [POST-PROCESSING] Manual post-processing completed for 1 issues.

**Comment by evilhero** [comment]
Are you using the comictagger included with Mylar? The reference to the error is indicating that either the comictagger.py  in the main root of mylar has been modified, or the lib/comictaggerlib is not the one that's included with Mylar.

Are you running this in a docker or something similar ?

**Comment by Baldrdk** [comment]
This is the log from a completely new install.  I wanted to make sure that I had not f'ed up anything in my setup.
And no docker or anything.

**Comment by evilhero** [comment]
Yes, I understand that it was a clean install but I had to still ask the question.

This line is the problem:
```
29-jul-2017 20:38:21 - DEBUG :: Thread-14 : [META-TAGGER] Running the ComicTagger Add-on for Mylar
29-jul-2017 20:38:22 - WARNING :: Thread-14 : [META-TAGGER][WARNING] Make sure that you are using the comictagger included with Mylar.
```
All it's trying to do is issue a simple `python comictagger.py --version` command and get the version number. It's saying it cannot do that - can you get to a command line and execute that command from within the main Mylar directory? It should return:
`python comictagger.py --version
ComicTagger 1.20.1 [ninjas.walk.alone / SHURIKEN]
Modified version of ComicTagger (Copyright (c) 2012-2014 Anthony Beville)
Distributed under Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
`

**Comment by Baldrdk** [comment]
I went old school on the problem, and got it working.
I uninstalled Python and all packages. And reinstalled the latest python 2.7.13.
And vola now it is working.
