### ISSUE TITLE
Torrent error snatch from WWT RSS

### ISSUE THREAD

**Issue by antdesca** [evilhero/mylar#1712]
Hi, 

I am on the development branch on latest commit.
When i try to snatch on this week releases i got this error (I activated debug logs). I am on a CET timezone.

```
2017-09-13 19:08:24 | ERROR | Uncaught exception: Traceback (most recent call last):File "/opt/mylar/mylar/logger.py", line 165, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "/opt/mylar/mylar/webserve.py", line 1465, in queueissuefoundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)File "/opt/mylar/mylar/search.py", line 243, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, oneoff=oneoff)File "/opt/mylar/mylar/search.py", line 1626, in NZB_SEARCHsearchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)File "/opt/mylar/mylar/search.py", line 2266, in searcherrcheck = rsscheck.torsend2client(ComicName, IssueNumber, comyear, link, nzbprov, nzbid) #nzbid = hash for usage with public torrentsFile "/opt/mylar/mylar/rsscheck.py", line 1162, in torsend2clientif nzbprov == 'TPSE':NameError: global name 'nzbprov' is not defined
-- | -- | --
2017-09-13 19:08:24 | DEBUG | [WWT] Saved torrent file to : /raid/downloads/transmission/watch/Ben_Reilly_Scarlet_Spider_7_2017.torrent
2017-09-13 19:08:18 | DEBUG | Grabbing torrent [id:109968] from url:https://worldwidetorrents.me/download.php
2017-09-13 19:08:18 | DEBUG | filename for torrent set to : /raid/downloads/transmission/watch/Ben_Reilly_Scarlet_Spider_7_2017.torrent
2017-09-13 19:08:18 | INFO | matched on Ben Reilly: Scarlet Spider
2017-09-13 19:08:18 | DEBUG | Torrent Provider:WWT
2017-09-13 19:08:18 | DEBUG | link:109968
2017-09-13 19:08:18 | DEBUG | ComicName:Ben Reilly: Scarlet Spider
2017-09-13 19:08:18 | DEBUG | link given by: WWT
2017-09-13 19:08:18 | INFO | Found Ben Reilly: Scarlet Spider (2017) issue: 7 using WWT [RSS]
2017-09-13 19:08:18 | DEBUG | issues match!
2017-09-13 19:08:18 | INFO | entry: {'length': u'70862766', 'link': u'109968', 'site': u'WWT', 'pubdate': u'Wed, 13 Sep 2017 16:25:57 +0100', 'title': u'Ben Reilly - Scarlet Spider 007 (2017) (Digital) (Zone-Empire).cbr'}
2017-09-13 19:08:18 | DEBUG | nzbname used for post-processing:Ben.Reilly.-.Scarlet.Spider.007.(2017).(Digital).(Zone-Empire).cbr
```

**Comment by evilhero** [comment]
Yep, that was an incorrect variable being referenced. Fixed now in latest dev commit

**Comment by antdesca** [comment]
Thanks for the quick fix !
Unfortunately, I still get another error. When i forced refreshed the RSS the torrents started as expected but when i tried to for search manually from the comics page i had this exception

```
Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 165, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/webserve.py", line 1465, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/opt/mylar/mylar/search.py", line 243, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, oneoff=oneoff)
File "/opt/mylar/mylar/search.py", line 1626, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "/opt/mylar/mylar/search.py", line 2266, in searcher
rcheck = rsscheck.torsend2client(ComicName, IssueNumber, comyear, link, nzbprov, nzbid) #nzbid = hash for usage with public torrents
File "/opt/mylar/mylar/rsscheck.py", line 1166, in torsend2client
torrent_info = helpers.get_the_hash(filepath)
File "/opt/mylar/mylar/helpers.py", line 2973, in get_the_hash
torrent_file = open(filepath, "rb")
IOError: [Errno 2] Aucun fichier ou dossier de ce type: u'/raid/downloads/transmission/watch/Generations_Captain_Marvel_&_Captain_Mar-vell_1_2017.torrent'
```

the french part means "no file or folder from this type"

**Comment by evilhero** [comment]
Is there a file in that location that's named that or is perhaps named something different (maybe missing a character or something)?

Also, there's built-in transmission support - is there a reason why you're not utilizing that method as opposed to the watchdir method ?

**Comment by antdesca** [comment]
You got it, i already had the file in the folder (from previous tests) 👍 

As i always remain on the development branch, i had in the past some issues (a few regressions) with the transmission support and i switched back to watchdir and never thought of coming back :)
