### ISSUE TITLE
'TorrentClient' object has no attribute 'client'

### ISSUE THREAD

**Issue by wicud** [evilhero/mylar#1777]
I'm getting this error on everything I've tried to download today.

Not sure if it's on my end or what.  I didn't change anything other than installing the most recent development branch update.

2017-11-22 17:45:46 | INFO | pausing for 60 seconds before continuing to avoid hammering
-- | -- | --
2017-11-22 17:45:46 | INFO | Shhh be very quiet...I'm looking for Action Comics issue: 992 (2018) using nzb.su
2017-11-22 17:45:46 | INFO | Could not find Issue 992 of Action Comics (2016) using 32P [api]
2017-11-22 17:45:46 | ERROR | Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
2017-11-22 17:45:46 | ERROR | 'TorrentClient' object has no attribute 'client'
2017-11-22 17:45:46 | INFO | filepath to torrent file set to : C:\Mylar\cache\Action_Comics_992_2018.torrent
2017-11-22 17:45:46 | INFO | Connected to qBittorrent! Will try to add torrent now!
2017-11-22 17:45:46 | ERROR | Could not create qBittorrent ObjectInvalid URL '8080/query/preferences': No schema supplied. Perhaps you meant http://8080/query/preferences?
2017-11-22 17:45:46 | INFO | 8080
2017-11-22 17:45:46 | INFO | payload: {'action': 'download', 'authkey': 'PRIVATE', 'id': u'57044', 'torrent_pass': 'PRIVATE'}
2017-11-22 17:45:46 | INFO | url: https://32pag.es/torrents.php
2017-11-22 17:45:46 | INFO | matched on Action Comics
2017-11-22 17:45:46 | INFO | Found Action Comics (2018) issue: 992 using 32P
2017-11-22 17:45:46 | INFO | successfully retrieved 2 search results.
2017-11-22 17:45:45 | INFO | payload: {'action': 'groupsearch', 'issue': u'992', 'id': u'478'}
2017-11-22 17:45:45 | INFO | 1 series match the tile being searched for on 32P...
2017-11-22 17:45:45 | INFO | dataset: [{'series': u'Action Comics', 'id': u'478'}]
2017-11-22 17:45:45 | INFO | Exact series ID already discovered previously. Setting to :Action Comics[478]
2017-11-22 17:45:45 | INFO | publisher search set to : DC
2017-11-22 17:45:45 | INFO | inkdrops: {u'status': u'success', u'results': [{u'inkdrops': u'2983752.1893', u'userid': PRIVATE}]}
2017-11-22 17:45:44 | INFO | Shhh be very quiet...I'm looking for Action Comics issue: 992 (2018) using 32P

**Comment by evilhero** [comment]
That's weird - I don't remember changing anything with the qbittorrent stuff, but the massive config changes might be causing some of the issues. Can I ask what your qbittorrent_host is set to in the config.ini ?

From the log (and I'm not sure how accurate that is), it looks like it's just set to the port # for some reason....

**Comment by wicud** [comment]
That was the problem.  I changed it to http://localhost:8080 and it's working.

I should backtrack.  I have always just used Local Watch Directory option for my torrents.

This morning I was getting the following on every torrent, which led me to change to the qbittorrent option and start fighting it.


2017-11-22 19:21:58 | INFO | Could not find Issue 35 of The Flash (2016) using 32P [api]
-- | -- | --
2017-11-22 19:21:58 | ERROR | Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
2017-11-22 19:21:58 | ERROR | No Local Watch Directory or Seedbox Watch Directory specified. Set it and try again.
2017-11-22 19:21:58 | INFO | matched on Flash
2017-11-22 19:21:58 | INFO | Found Flash (2018) issue: 35 using 32P
2017-11-22 19:21:58 | INFO | successfully retrieved 5 search results.
2017-11-22 19:21:57 | INFO | payload: {'action': 'groupsearch', 'issue': u'35', 'id': u'48'}
2017-11-22 19:21:57 | INFO | 1 series match the tile being searched for on 32P...
2017-11-22 19:21:57 | INFO | dataset: [{'series': u'Flash', 'id': u'48'}]
2017-11-22 19:21:57 | INFO | Exact series ID already discovered previously. Setting to :Flash[48]
2017-11-22 19:21:57 | INFO | publisher search set to : DC
2017-11-22 19:21:57 | INFO | inkdrops: {u'status': u'success', u'results': [{u'inkdrops': u'2983809.0557', u'userid': 20418}]}
2017-11-22 19:21:57 | INFO | Shhh be very quiet...I'm looking for Flash issue: 35 (2018) using 32P
2017-11-22 19:21:57 | INFO | Alternate Search pattern detected...re-adjusting to : Flash
2017-11-22 19:21:57 | ERROR | Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
2017-11-22 19:21:57 | ERROR | No Local Watch Directory or Seedbox Watch Directory specified. Set it and try again.
2017-11-22 19:21:57 | INFO | matched on The Flash
2017-11-22 19:21:57 | INFO | Found The Flash (2018) issue: 35 using 32P
2017-11-22 19:21:57 | INFO | successfully retrieved 5 search results.

My config file shows:

[Watchdir]
torrent_local = True
local_watchdir = C:\Users\wicud\Downloads

But in the Mylar GUI:

I select the Watchdir radio button.

I click the checkbox next to Local Watch Dir.

The textbox shows my local folder.

I click the Save button.

The Local Watch Dir checkbox automatically unchecks.

My config file still shows 

[Watchdir]
torrent_local = True
local_watchdir = C:\Users\wicud\Downloads

This could be an oddity in my setup, I don't know.

But with the update to my qbittorrent host I'm able to download, so I'm happy :)

**Comment by evilhero** [comment]
Wow - we missed that one entirely. You're correct - if you saved the config when you had the Local Watch Dir option enabled, it would disable it after the save. 

This has been fixed now in 7be5b02 (the most recent development commit)...

Thanks for the detailed follow-up so I could fix it ;)

**Comment by wicud** [comment]
Glad I could help.

Thanks for the quick responses as always :)

**Comment by MrDemous** [comment]
I'm facing this problem as well. I'm on the latest development build and it's still not working for me 


2017-12-11 05:01:08 | ERROR | Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
-- | -- | --
2017-12-11 05:01:08 | ERROR | 'TorrentClient' object has no attribute 'client'
2017-12-11 05:01:08 | INFO | filepath to torrent file set to : c:\Mylar\cache\Paper_Girls_14_2017.torrent
2017-12-11 05:01:08 | INFO | Connected to qBittorrent! Will try to add torrent now!
2017-12-11 05:01:08 | ERROR | Could not create qBittorrent ObjectNo connection adapters were found for 'localhost:8867/query/preferences'

I'm not sure what is wrong and I have no idea how to get it to work.

**Comment by evilhero** [comment]
Make sure you preface the qbittorrent host with the protocol (http or https), so it forms a valid web url.

**Comment by MrDemous** [comment]
That did it. Thanks evilhero :D
