### ISSUE TITLE
C.O.W.L. not being loaded 

### ISSUE THREAD

**Issue by PCurd** [evilhero/mylar#1880]
I noticed after a restart that C.O.W.L. was putting errors in the logs when being refreshed and inside the interface it was showing as (Comic information is still being loaded). I added this comic months and months ago so tried to Refresh Comic, but nothing changed. I then deleted the comic and re added from the ComicVine ID (it's hard to search for with a name like that - https://comicvine.gamespot.com/c-o-w-l/4050-74313/) and it added but is now looking even worse - the list of issues isn't even loading. The logs are below. I noted the InsecureRequestWarning but I can't fix the damn error and I've had it for ages, I've tried pip.exe install requests[security] --upgrade but that didn't fix it. 

This is what appears in the logs:

05-Mar-2018 11:28:18 - INFO :: CP Server Thread-3 : Attempting to add directly by ComicVineID: 74313. I sure hope you know what you are doing.
05-Mar-2018 11:28:18 - WARNING :: CP Server Thread-3 : Comic ID: 74313 has not finished loading. Nulling some values so things display properly until they can populate.
D:\Mylar\mylar\lib\requests\packages\urllib3\connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
05-Mar-2018 11:28:21 - INFO :: Thread-14 : Now adding/updating: C.O.W.L.
05-Mar-2018 11:28:21 - INFO :: Thread-14 : Sucessfully retrieved details for C.O.W.L.
05-Mar-2018 11:28:21 - INFO :: Thread-14 : Previous version detected as None - seeing if update required
05-Mar-2018 11:28:21 - INFO :: Thread-14 : Directory (M:\Comics\C.O.W.L. (2014)) already exists! Continuing...
05-Mar-2018 11:28:23 - INFO :: Thread-14 : Attempting to retrieve the comic image for series
D:\Mylar\mylar\lib\requests\packages\urllib3\connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
05-Mar-2018 11:28:24 - ERROR :: Thread-14 : Uncaught exception: Traceback (most recent call last):
  File "D:\Mylar\mylar\mylar\logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Mylar\mylar\mylar\importer.py", line 265, in addComictoDB
    covercheck = helpers.getImage(comicid, comic['ComicImage'])
  File "D:\Mylar\mylar\mylar\helpers.py", line 3419, in getImage
    buf = StringIO(r.content)
NameError: global name 'StringIO' is not defined

Traceback (most recent call last):
  File "D:\Mylar\mylar\mylar\logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Mylar\mylar\mylar\importer.py", line 265, in addComictoDB
    covercheck = helpers.getImage(comicid, comic['ComicImage'])
  File "D:\Mylar\mylar\mylar\helpers.py", line 3419, in getImage
    buf = StringIO(r.content)
NameError: global name 'StringIO' is not defined
05-Mar-2018 11:28:25 - WARNING :: CP Server Thread-3 : Comic ID: 74313 has not finished loading. Nulling some values so things display properly until they can populate.
05-Mar-2018 11:28:54 - INFO :: CP Server Thread-2 : Attempting to add directly by ComicVineID: 74313. I sure hope you know what you are doing.
05-Mar-2018 11:28:54 - ERROR :: Thread-15 : Uncaught exception: Traceback (most recent call last):
  File "D:\Mylar\mylar\mylar\logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Mylar\mylar\mylar\importer.py", line 84, in addComictoDB
    checkdirectory = filechecker.validateAndCreateDirectory(comlocation, True)
  File "D:\Mylar\mylar\mylar\filechecker.py", line 1338, in validateAndCreateDirectory
    if os.path.exists(dir):
  File "c:\python27\lib\genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

Traceback (most recent call last):
  File "D:\Mylar\mylar\mylar\logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Mylar\mylar\mylar\importer.py", line 84, in addComictoDB
    checkdirectory = filechecker.validateAndCreateDirectory(comlocation, True)
  File "D:\Mylar\mylar\mylar\filechecker.py", line 1338, in validateAndCreateDirectory
    if os.path.exists(dir):
  File "c:\python27\lib\genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by evilhero** [comment]
Should be all fixed now in dev.

As far as your insecure security warnings, try setting the cv_verify = True in the config.ini. That will force Mylar to verify the secure connection to CV, which is what that warning is saying (the warning doesn't stop things, it just spams the console until it gets fixed)

**Comment by PCurd** [comment]
After updating (and setting cv_verify to True) I'm getting a different error now. I tried deleting C.O.W.L. again and then restarting, but after searching for the CV number I still get the error:

06-Mar-2018 10:09:21 - INFO :: CP Server Thread-2 : Attempting to add directly by ComicVineID: 74313. I sure hope you know what you are doing.
06-Mar-2018 10:09:21 - WARNING :: CP Server Thread-2 : Comic ID: 74313 has not finished loading. Nulling some values so things display properly until they can populate.
06-Mar-2018 10:09:24 - INFO :: Thread-12 : Now adding/updating: C.O.W.L.
06-Mar-2018 10:09:24 - INFO :: Thread-12 : Sucessfully retrieved details for C.O.W.L.
06-Mar-2018 10:09:24 - INFO :: Thread-12 : Previous version detected as None - seeing if update required
06-Mar-2018 10:09:24 - INFO :: Thread-12 : Directory (M:\Comics\C.O.W.L. (2014)) already exists! Continuing...
06-Mar-2018 10:09:26 - INFO :: Thread-12 : Attempting to retrieve the comic image for series
06-Mar-2018 10:09:28 - ERROR :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "D:\Mylar\mylar\mylar\logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Mylar\mylar\mylar\importer.py", line 264, in addComictoDB
    covercheck = helpers.getImage(comicid, comic['ComicImage'])
  File "D:\Mylar\mylar\mylar\helpers.py", line 3420, in getImage
    f = gzip.GzipFile(fileobj=buf)
NameError: global name 'gzip' is not defined

Traceback (most recent call last):
  File "D:\Mylar\mylar\mylar\logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Mylar\mylar\mylar\importer.py", line 264, in addComictoDB
    covercheck = helpers.getImage(comicid, comic['ComicImage'])
  File "D:\Mylar\mylar\mylar\helpers.py", line 3420, in getImage
    f = gzip.GzipFile(fileobj=buf)
NameError: global name 'gzip' is not defined

After trying to add it again without a restart, I get this (different) error:

06-Mar-2018 10:10:05 - INFO :: CP Server Thread-10 : Attempting to add directly by ComicVineID: 74313. I sure hope you know what you are doing.
06-Mar-2018 10:10:05 - ERROR :: Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "D:\Mylar\mylar\mylar\logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Mylar\mylar\mylar\importer.py", line 83, in addComictoDB
    checkdirectory = filechecker.validateAndCreateDirectory(comlocation, True)
  File "D:\Mylar\mylar\mylar\filechecker.py", line 1338, in validateAndCreateDirectory
    if os.path.exists(dir):
  File "c:\python27\lib\genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

Traceback (most recent call last):
  File "D:\Mylar\mylar\mylar\logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Mylar\mylar\mylar\importer.py", line 83, in addComictoDB
    checkdirectory = filechecker.validateAndCreateDirectory(comlocation, True)
  File "D:\Mylar\mylar\mylar\filechecker.py", line 1338, in validateAndCreateDirectory
    if os.path.exists(dir):
  File "c:\python27\lib\genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by evilhero** [comment]
K, should be fixed hopefully now.

The error you're getting after you've already tried to add it and failed is due to the series not being complete, so when it references it in the db (because it thinks it's there) it's failling to lookup. With the above fix in place, you shouldn't be getting those anymore.

**Comment by PCurd** [comment]
Yep that did it, thanks!
