### ISSUE TITLE
error when trying to rename the issues of a series

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1927]
tried to rename all avengers issues and i'm getting this error

2018-04-20 18:25:52 | ERROR | Failed to move files - check directories and manually re-run.
-- | -- | --
2018-04-20 18:25:52 | INFO | Renaming Avengers 679 (2018).cbr ... to ... Avengers #679 (2018).cbr
2018-04-20 18:25:52 | DEBUG | Destination: Z:\Comics\SORTED\MARVEL\AVENGERS\AVENGERS\AVENGERS\Avengers (2016)\Avengers #679 (2018).cbr

the moving of files after a download works as it should, what exactly can i check?

running current master on windows 10.

**Comment by HypKin** [comment]
also other series are working... seems to be a specific problem for this folder?

**Comment by evilhero** [comment]
Update your master - I just merged dev into master about 20 mins ago.

I believe this should be fixed now, but if not - can you enable debug logging and see what the logs report back?

**Comment by evilhero** [comment]
Is the destination path suppose to be ```Z:\Comics\SORTED\MARVEL\AVENGERS\AVENGERS\AVENGERS\Avengers (2016)\```?

Can you confirm what your series directory is for the given  series within mylar.

**Comment by HypKin** [comment]
even after the update its still not working.

yes that is the directory

![image](https://user-images.githubusercontent.com/15702664/39082641-c20d16bc-4556-11e8-9643-91dc22e58fed.png)

**Comment by HypKin** [comment]
yes, the first one contains all avengers and typical avengers members' comics (cap, iron man, hulk, ant man..) the second level contains all kinds of avengers and avengers auxillery comics (like avengers a.i. for example) and the third level contains only the major avengers series, like all volumes of avengers, mighty avengers, new avengers.

so I did this on purpose. do you think this is messing it up?

**Comment by evilhero** [comment]
Are the perms correct on all the folder levels? It might be messing it up, but that might be due to a folder format problem (you manually updated the path, but it's trying to force its folder format into it for some reason).

**Comment by evilhero** [comment]
Im pretty sure at this point, that it's trying to move the file to the comic location + folder format path. Which you're not following cause you entered it in manually - I'll have to do some code change later as it should be taking a manually entered path as precedence over anything else. Hopefully later tonight I can get things fixed so it's not a further problem going forward.

**Comment by evilhero** [comment]
This might be related to #1928 - what happens is that if it encounters a filename that is already in the renamed format, it skips it as a rename - but logs it as a FAILURE so to distinguish it from an actual successful rename. The error that was occuring was that the log line to return the FAILURE filenames, was in an incorrect format resulting in a traceback. The fix for this is in both master/development now, so give it a try and see if it fixes it (if you still have the files as they were of course).

**Comment by HypKin** [comment]
i may have to apologise, after the update it still didn't work but i took a look again at the files...

well it seems like either the renaming worked at some point but the deleting of the old files didn't OR something like a double download?

so the renaming stopped because there already was an issue with the name that it tried to rename the issue to, and then it just stopped at some point.

so only 2 files didn't have the correct naming but 15 were duplicates.
